<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Test Started!!]]>
    </line>
    <line>
      <![CDATA[Browser Opened & Test Will Start!!]]>
    </line>
    <line>
      <![CDATA[Test falied due to :validTestCase]]>
    </line>
  </reporter-output>
  <suite started-at="2023-06-02T16:22:43 IST" name="Default suite" finished-at="2023-06-02T16:24:52 IST" duration-ms="128904">
    <groups>
    </groups>
    <test started-at="2023-06-02T16:22:43 IST" name="Default test" finished-at="2023-06-02T16:24:52 IST" duration-ms="128904">
      <class name="testPackage.ValidLoginTestCase">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testPackage.ValidLoginTestCase@769f71a9]" started-at="2023-06-02T16:22:43 IST" name="setUp" finished-at="2023-06-02T16:23:23 IST" duration-ms="39785" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validTestCase()[pri:0, instance:testPackage.ValidLoginTestCase@769f71a9]" started-at="2023-06-02T16:23:23 IST" name="validTestCase" finished-at="2023-06-02T16:24:49 IST" duration-ms="85543" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sheet" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sheet" is null
at genericPackage.Flib.readExcelData(Flib.java:26)
at testPackage.ValidLoginTestCase.validTestCase(ValidLoginTestCase.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[Browser Opened & Test Will Start!!]]>
            </line>
            <line>
              <![CDATA[Test falied due to :validTestCase]]>
            </line>
          </reporter-output>
        </test-method> <!-- validTestCase -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testPackage.ValidLoginTestCase@769f71a9]" started-at="2023-06-02T16:24:50 IST" name="tearDown" finished-at="2023-06-02T16:24:52 IST" duration-ms="2658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testPackage.ValidLoginTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
